### ISSUE TITLE
Error: no such table: meetings

### ISSUE THREAD

**Issue by sadokx** [lanec/zoom-batch-downloader#31]
I just get this error when running the script. Thanks!

**Comment by ggatto** [comment]
Can you share more information about the error?

**Comment by sadokx** [comment]
This is what i get: 
<img width="553" alt="image" src="https://github.com/lanec/zoom-batch-downloader/assets/12555077/8ea5ae87-9e33-42d3-afba-6b7499534c89">

**Comment by AnessZurba** [comment]
Please enable verbose output in the config file

**Comment by sadokx** [comment]
Here you go @AnessZurba @ggatto , thanks for the help:

```Traceback (most recent call last):
  File "/Users/sadok/Downloads/zoom-batch-downloader-master/zoom_batch_downloader.py", line 218, in get_meetings
    cursor.execute("DELETE FROM meetings WHERE uuid = ?", (meeting_uuid,))
sqlite3.OperationalError: no such table: meetings

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sadok/Downloads/zoom-batch-downloader-master/zoom_batch_downloader.py", line 369, in <module>
    main()
  File "/Users/sadok/Downloads/zoom-batch-downloader-master/zoom_batch_downloader.py", line 53, in main
    file_count, total_size, skipped_count = download_recordings(
  File "/Users/sadok/Downloads/zoom-batch-downloader-master/zoom_batch_downloader.py", line 130, in download_recordings
    meetings = get_meetings(get_meeting_uuids(user_email, from_date, to_date))
  File "/Users/sadok/Downloads/zoom-batch-downloader-master/zoom_batch_downloader.py", line 220, in get_meetings
    cursor.execute(
sqlite3.OperationalError: no such table: meetings```

**Comment by AnessZurba** [comment]
This may sound weird, but are you sure you are using code from this
repository

**Comment by AnessZurba** [comment]
nvm. I see some code was added

**Comment by asamihassan** [comment]
Hi all,
Fixing it in the next commit.

**Comment by sadokx** [comment]
Thanks @asamihassan , just curious, any expectation on when that commit will come through? Thanks!

**Comment by asamihassan** [comment]
@sadokx please pull the new code. It's there.
